#!/usr/bin/env node
const fs=require("fs");
const os=require("os");
const path=require("path");
const {execFileSync}=require("child_process");
const ROOT=path.resolve(__dirname,"..");
const failures=[];
const read=relative=>fs.readFileSync(path.join(ROOT,relative),"utf8");
const check=(name,condition,detail)=>{if(!condition)failures.push(`${name}: ${detail}`)};
function syntax(relative){const temporary=path.join(os.tmpdir(),`evaraos-${path.basename(relative,".js")}-${process.pid}.mjs`);try{fs.writeFileSync(temporary,read(relative),"utf8");execFileSync(process.execPath,["--check",temporary],{stdio:"pipe"})}catch(error){failures.push(`${relative}: JavaScript syntax check failed\n${String(error.stderr||error.message)}`)}finally{try{fs.rmSync(temporary,{force:true})}catch{}}}
const javascriptFiles=["public/assets/js/adaptive-appearance-boot.js","public/assets/js/theme-adaptive.js","public/assets/js/theme-text-inversion.js","public/assets/js/theme-core-adaptive.js","public/assets/js/theme.js","public/assets/js/nav.js","public/assets/js/nav/nav-main-v6.js","public/assets/js/nav/nav-render.js","public/assets/js/nav/nav-menu.js","public/assets/js/nav/nav-interactions.js","public/assets/js/nav/nav-bottom.js","public/assets/js/settings-appearance-v2.js","public/assets/js/ui-assets.js","public/assets/js/loader.js"];
javascriptFiles.forEach(syntax);
const menuCss=read("public/assets/css/nav/nav-menu-liquid.css");
const stabilityCss=read("public/assets/css/nav/nav-stability.css");
const cleanControls=read("public/assets/css/nav/nav-menu-clean-controls.css");
const bottomCss=read("public/assets/css/nav/nav-bottom.css");
const navRender=read("public/assets/js/nav/nav-render.js");
const materialCss=read("public/assets/css/theme/liquid-optics.css");
const { assets, pageFailures } = require("./lib/ui-contract.cjs");
const componentsCss=read("public/assets/css/theme/adaptive-components.css");
const adaptiveJs=read("public/assets/js/theme-adaptive.js");
const textJs=read("public/assets/js/theme-text-inversion.js");
const bootJs=read("public/assets/js/adaptive-appearance-boot.js");
const navEntry=read("public/assets/js/nav.js");
const navMainEntry=read("public/assets/js/nav/nav-main-v6.js");
const navSessionEntry=read("public/assets/js/nav/nav-session.js");
const settingsAppearanceEntry=read("public/assets/js/settings-appearance-v2.js");
const settingsAppearancePage=read("public/settings/appearance.html");
const loaderJs=read("public/assets/js/loader.js");
const menuJs=read("public/assets/js/nav/nav-menu.js");
const themeEntry=read("public/assets/js/theme.js");
check("drawer-width",menuCss.includes("width:min(75vw,460px)"),"drawer must cover 75% of mobile width and remain capped on desktop");
check("drawer-origin",menuCss.includes("inset:0 auto 0 0")&&stabilityCss.includes("translate3d(-101%,0,0)"),"drawer must be full-height and enter from the left");
check("drawer-open",stabilityCss.includes("body.nav-menu-open .eva-menu-panel")&&stabilityCss.includes("translate3d(0,0,0)"),"open state must use one transform-only path");
check("hybrid-groups",navRender.includes("eva-menu-glass-group")&&menuCss.includes(".eva-menu-glass-group"),"Account and AI must remain intentional glass groups");
check("flat-categories",navRender.includes('<section class="eva-app-section">')&&!navRender.includes('<section class="eva-app-section" data-glass='),"application categories must remain flat sections");
check("selected-menu-only",cleanControls.includes('[data-active="true"]')&&materialCss.includes(".eva-menu-control:not([data-active=\"true\"]):not(.is-pressed)"),"menu rows must be transparent except selected or pressed states");
check("selected-bottom-only",bottomCss.includes('.eva-bottom-link.is-active')&&materialCss.includes('.eva-bottom-link:not(.is-active):not([aria-current="page"]):not(.is-pressed)'),"bottom-nav links must be transparent except the current page");
check("single-material-painter",!componentsCss.includes("backdrop-filter:"),"fields and modal material must be painted by liquid-optics");
check("no-difference-blend",!componentsCss.includes("mix-blend-mode:difference")&&!adaptiveJs.includes("mix-blend-mode:difference"),"text inversion must not use difference blending");
check("seven-text-stops",componentsCss.includes("@property --adaptive-text-c6")&&/TEXT_X\s*=\s*\[0?\.02,\s*0?\.18,\s*0?\.34,\s*0?\.5,\s*0?\.66,\s*0?\.82,\s*0?\.98\]/.test(adaptiveJs),"text gradients must use seven context-aware sample points");
check("context-aware-text",/function backgroundAt\(element,\s*x,\s*y,\s*includeSurface\s*=\s*true\)/.test(adaptiveJs)&&adaptiveJs.includes("getComputedStyle"),"text contrast must account for ancestor backgrounds and glass");
check("cached-pixels",/pixels\s*=\s*\w+\.getImageData\(/.test(adaptiveJs),"adaptive text must sample from a cached pixel buffer");
check("all-text-coverage",textJs.includes("createTreeWalker")&&textJs.includes("NodeFilter.SHOW_TEXT"),"all visible text nodes must be wrapped for adaptive gradients");
check("paint-lock",bootJs.includes("evara-boot-lock")&&bootJs.includes("evara-theme-painted"),"startup must hide legacy paint until adaptive CSS is active");
check("nav-build",navEntry.includes(new URL(assets.navRuntime,"https://ui.invalid").searchParams.get("v")),"navigation entry must match the shared contract");
check("nav-main-build",navEntry.includes("./nav/nav-main-v6.js?v=universal-a11y-2"),"navigation entry must load the current module graph");
check("nav-events-build",navMainEntry.includes("./nav-events.js?v=nav-events-universal-2"),"navigation event binding must use a versioned module URL");
check("nav-session-build",navMainEntry.includes("./nav-session.js?v=nav-session-universal-2"),"navigation session binding must load the current module revision");
check("nav-session-events-build",navSessionEntry.includes("./nav-events.js?v=nav-events-universal-2"),"session refresh must reuse the current navigation event binder");
check("theme-build",themeEntry.includes(new URL(assets.themeRuntime,"https://ui.invalid").searchParams.get("v")),"theme entry must match the shared contract");
check("appearance-api",["saveAppearance","resetAppearance","VALID_MODES","getEffectiveWallpaper"].every(name=>themeEntry.includes(`export const ${name} = Core.${name}`)),"Appearance imports must be exported by the shared theme facade");
check("appearance-entry-build",settingsAppearancePage.includes("/assets/js/settings-appearance-v2.js?v=7"),"Appearance page must load the current control module");
check("appearance-theme-build",settingsAppearanceEntry.includes(`./theme.js${new URL(assets.themeRuntime,"https://ui.invalid").search}`),"Appearance controls must reuse the canonical theme facade URL");
check("prepaint-updates",bootJs.includes("background:var(--evara-wallpaper-canvas)"),"prepaint must consume live wallpaper variables");
check("stable-semantic-ink",componentsCss.includes('html[data-environment="image"][data-adaptive-contrast="on"] .evara-adaptive-text-node'),"text gradients must be limited to adaptive image appearance");
check("watchdog-asset-contract",loaderJs.includes('UI_ASSETS.navRuntime')&&!loaderJs.includes('nav.js?v='),"loader recovery must use the same nav URL as the page");
check("drawer-modal-focus",menuJs.includes('event.key === "Tab"')&&menuJs.includes('event.key === "Escape"')&&menuJs.includes('sibling.inert = true')&&menuJs.includes('btn.focus({ preventScroll: true })'),"the drawer must isolate background interaction, contain focus and restore it when closed");
const htmlFiles=[];function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full);else if(entry.name.endsWith(".html"))htmlFiles.push(full)}}walk(path.join(ROOT,"public"));
for(const file of htmlFiles){const html=fs.readFileSync(file,"utf8"),relative=path.relative(path.join(ROOT,"public"),file).replace(/\\/g,"/");failures.push(...pageFailures(html,relative))}
if(failures.length){console.error(`Interface audit failed with ${failures.length} issue(s):`);failures.forEach(failure=>console.error(`- ${failure}`));process.exit(1)}
console.log(`Interface audit passed: ${javascriptFiles.length} JavaScript files, ${htmlFiles.length} HTML pages and current architecture contracts.`);
